- README.MD
- lib/generate-report.js
- templates/components/scenarios-overview.chart.tmpl
- templates/style.css
- test/unit/data/collect-json/no-metadata.json
- test/unit/data/json/ambiguous_scenarios_specified_v1.json
- test/unit/data/json/ambiguous_scenarios_specified_v2.json
- test/unit/data/json/ambiguous_scenarios_specified_v3.json
- test/unit/data/json/failure_report_v1.json
- test/unit/data/json/failure_report_v2.json
- test/unit/data/json/failure_report_v3.json
- test/unit/data/json/no_elements.json
- test/unit/data/json/pending_scenarios_specified_v1.json
- test/unit/data/json/pending_scenarios_specified_v2.json
- test/unit/data/json/pending_scenarios_specified_v3.json
- test/unit/data/json/skipped_scenarios.json
- test/unit/data/json/undefined_scenarios_specified_v1.json
- test/unit/data/json/undefined_scenarios_specified_v2.json
- test/unit/data/json/undefined_scenarios_specified_v3.json
- test/unit/data/output/merged-output.json
- test/unit/data/output/provided-metadata.json
A small set of changes to use the correct plural form of 'scenario' in the generated reports and tests.  Also swaps 'No elements have been founds' for 'No elements have been found'.
> chore: Fixes typos

- README.MD
A small update to the Usage documentation to indicate that `AfterFeatures` does not work in cucumber-js 3.x and it should be run in a separate node process.
Also a small typo error fix.
> Added information for usage in cucumber-js 3.x

- lib/generate-report.js
- templates/components/features-overview.chart.tmpl
- templates/components/features-overview.tmpl
- templates/features-overview.index.tmpl
This is the PR for #20.
I've updated the features chart on the home page to include skipped:
And updated the status column on the features table:
Today is my last day in the office until 3rd January.  If there's any comments / changes, I'll pick them up after Christmas.
> fix: correctly show the skipped features on the report home page

- package.json
- templates/components/feature-metadata-overview.tmpl
- templates/components/features-overview.tmpl
- test/unit/data/json/happy_flow_v3.json
- test/unit/data/output/merged-output.json
This is the fix for #25.
I've updated the templates, and one of the json result files to test that it renders correctly with `npm run test`
As you can see it renders correctly now:
> fix: show edge icon for tests run with microsoft edge

- lib/generate-report.js
- test/unit/data/custom-metadata-json/multiple_different_attachements.json
This fixes having multiple attachments for a single step (if they are not all plain texts)
I also added mime type check for 'application/json' because it is officially recomended way of attaching jsons from cucumber-js, as desribed [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md)
I made **step.text** an array because it is the most obvious way to have attachments of different types (plain text and json) displayed together.
Added test json that was used to reproduce the problem as 
`test/unit/data/custom-metadata-json/multiple_different_attachements.json`
> fix of attaching multiple json and text attachments to the same step

- README.MD
- lib/generate-report.js
- package-lock.json
- templates/components/scenarios-overview.chart.tmpl
- templates/components/scenarios.tmpl
- templates/style.css
- test/test.js
PR for [the show duration issue](https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/11).
Adds support for duration display in a readable format.
> Show duration

- templates/features-overview.index.tmpl
Adds a save state to the columns under Features overview that will remember your sort order when you reload a page, or come back to the page after visiting a sub-page.
This is especially useful when you want to order by failed tests. You then would be able to sort by failed, click into a feature, look at what's wrong, navigate back, and click the next failed feature without needing to reapply the sort order.
https://datatables.net/examples/basic_init/state_save.html
> Add save sort state to columns under Features overview

- README.MD
- lib/generate-report.js
- templates/feature-overview.index.tmpl
- templates/features-overview.index.tmpl
added pageFooter - to customise Page Footer
updated reportName referring directly instead from suite, so able to display header in feature-overview.
updated README
> added pageTitle - to customise HTML head

- lib/generate-report.js
- templates/components/scenarios.tmpl
Cucumber allows saving of multiple images, but the report currently only displays the last image that was attached.
Updated the report to show all images attached to a step.
**Note:** I advise updating the css to better accommodate multiple images. Currently, small images will stretch to the width of the largest image - making them looked stretched,  and it's hard to tell where an image ends and another stops. In the screenshots below, you'll see how it looks with my custom css that I feel best displays the images. I'll gladly give you the css if you're wanting to copy and use it.
> Add support for multiple screenshots in scenario steps

- lib/collect-jsons.js
Fixes #47 
Specifically check for empty json and not ignoring *all* invalid json, because in some cases, you just want to see something is wrong.
> allow empty json reports instead of failing

- lib/generate-report.js
- templates/components/scenarios.tmpl
- test/unit/data/embedded-array-json/embedded_success_v1.json
This pull request allows the user to embed the `text/html` mime type, and have the embed data displayed, unescaped, in the scenario report.
The commit consists of 3 main changes:
1. Add a `text/html` mime_type handler to the if structure in `_parseSteps`. I just collects the data into a `.html` property on the step.
2. Add a relevant template structure to handle the `.html` property. It joins multiple attachments into a single HTML block, separated by a `<br/>` element.
3. Add an html embed step to the test data.
> Support for unescaped text/html embeds

- lib/collect-jsons.js
- test/unit/collect-jsons.spec.js
Also, added a unit test for safe measures.
> Made collect-jsons.js return an actual empty array instead of string.

- templates/components/scenarios.tmpl
@wswebcreation 
removed a href tag on template to avoid error generating html report while we have bigger image (raw) size
> Template update

- lib/generate-report.js
- templates/components/scenarios.tmpl
**Fix for the following issue:**
Embeddings of type text/plain can break the report if they include HTML tags
**Example**
Base64 content from *.cucumber.json:
```VGltZWQgb3V0IHJldHJ5aW5nOiBleHBlY3RlZCAnPHRhYmxlPicgbm90IHRvIGNvbnRhaW4gdGV4dCAnRGllc2UgQmVtZXJrdW5nIGRhcmYgbmllIGVyc2NoZWluZW4hJw==```
Decoded content in html report:
```Timed out retrying: expected '<table>' not to contain text 'Diese Bemerkung darf nie erscheinen!'```
**Result**
Report is cut off after step containing the decoded content, because everything else is rendered within a table.
> Added html escaping for opening and closing brackets in embedded text

- templates/components/features-overview-custom-metadata.tmpl
PR makes it so the Duration column is shown in the features overview even if customMetadata is set to true when displayDuration is also set to true. I think it's nicer to enable this entry via displayDuration, rather than add the duration back as a new custom metadata field. 
I've put the column in the same place as it would be when not using custom metadata (I.e, after the custom metadata / App+Browser+etc info).
> Show duration in features overview when customMetadata is true

- templates/components/scenarios.tmpl
PR escapes the < > symbols with &lt and &gt to prevent them being interpreted as HTML. Could probably better escape this to catch other symbols, but for now this solves the original issue I had.
Fixes #106
> #106 Escape < and > with &lt/&gt

- lib/generate-report.js
- templates/components/scenarios.tmpl
- test/unit/data/json/with_rest_doc_string.json
- test/unit/data/output/merged-output.json
As a user who uses karate service based testing framework (https://intuit.github.io/karate/), I wanted to see the http wire request and response when my test execute. 
The PR will add this capability. The karate generated json, will add a `doc_string` node to step which contains the wire log. The log is being parsed and emitted in the report.
The report will add a new button in the report 
And expands upon click will show the wire request and response with headers
> Added capability to show REST response in report 

- lib/generate-report.js
- test/unit/data/custom-metadata-json/multiple_different_attachements.json
Hello, I recently ran into an issue in my automation framework where the error below was being thrown.
```log
TypeError: string.replace is not a function
at _escapeHtml (/var/lib/jenkins/workspace/msg-wdio-automated-tests/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:453:17)
at step.embeddings.forEach (/var/lib/jenkins/workspace/msg-wdio-automated-tests/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:341:81)
at Array.forEach (<anonymous>)
at scenario.steps.forEach.step (/var/lib/jenkins/workspace/msg-wdio-automated-tests/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:330:21)
at Array.forEach (<anonymous>)
at _parseSteps (/var/lib/jenkins/workspace/msg-wdio-automated-tests/node_modules/multiple-cucumber-html-reporter/lib/generat …
```
> Update _escapeHtml to only replace html characters if passed in string is actually a string

- templates/components/feature-metadata-overview.tmpl
- templates/components/features-overview.tmpl
Hi,
For my project I have, the 'browsername' metadata is set as 'msedge' instead of 'edge' or 'microsoftedge'. I'm using WebdriverIO v6, which (at this moment) does not support changing the metadata for the cucumberJS JSON.
I thought the easiest way to solve this is to make 'msedge' an option for the correct browser icon as well.
> Make browsername 'msedge' cause correct browser icon instead of '?'

- .gitignore
- .vscode/launch.json
- README.MD
- lib/collect-jsons.js
- lib/generate-report.js
- templates/components/features-overview.tmpl
- test/test.js
- test/unit/collect-jsons.spec.js
- test/unit/generate-json.spec.js
The purpose of this PR is to be able to display the date and time at which the JSON-files were generated. 
A new option called `displayReportTime` has been created for this purpose.
When this option is set to `true`, a new column called `Date` will be added in the Features Overview, just beside the `Duration` column.
This column will display the creation date of the corresponding JSON-file. 
The date is formatted like this: `YYYY/MM/DD HH:mm:ss`, so that the user can sort the report by dates ascending or descending.
> feat(reporter): be able to display the date and time at which the JSON-files were generated

- templates/components/features-overview.tmpl
I wanted to search for the tags of my scenarios in features form the main screens search bar. With the current implementation this is not possible. 
My fix adds the tags of the scenarios to the features overview table tags column and you can now search for tags of scenarios.
> Scenario tags now searchable

- lib/generate-report.js
`restWireData` was not being HTML escaped, which meant that if any HTML
was returned in a response (which is possible for non-RESTful HTTP requests),
that the HTML was embedding and messing up the HTML for the report page.
This change escapes any returned HTML.
In addition, `_escapeHtml` has also been made more strict, escaping
more than just `<` and `>` characters.
If this implementation is considered _too_ strict, we can modify it to
just replace the "major players" such as happens in [mustache.js](https://github.com/janl/mustache.js/blob/master/mustache.js#L60-L75)
> More aggresive `_escapeHtml`, and escape `restWireData`

- README.MD
- lib/generate-report.js
Fixes #170 
`metadata` field is overwritten in a feature only if not already set. In this way the `customMetadata` passed on CLI acts as a "default value" for the features that do not provide `metadata`. The `customMetadata` test output looks good to me.
I've added a note on the readme about the behaviour of `customMetadata` and fixed some typos while I was at it. :slightly_smiling_face:
Hope this is good enough. Thanks.
> #170 Ensure custom metadata is overwritten only if not set already

- README.MD
- templates/assets/js/Chart.style.js
- templates/feature-overview.index.tmpl
- templates/features-overview.index.tmpl
- test/custom.css
Fixes #176 
Introduces a `getChartColors` function to fetch the donut chart colors from CSS variables. Updates both the example and the documentation to mention the option.
I wasn't sure if we were happy with introducing CSS variables in the main css file. If we are ok with that, we can apply the changes I made to `custom.css` directly to `style.css`. In that way we can just easily customize everything in `custom.css` by just defining the CSS variables. Seems saner to me but, as I'm not a big expert on CSS, I leave that final decision to you @wswebcreation. :slightly_smiling_face:
> Add colors fetching function and use it with donuts

- lib/generate-report.js
- test/custom.css
Fixes #184 
Moves the `pageFooter` option back while aligning `customMetadata` to the other `boolean` options. I've also hidden the darkmode toggle in the custom `CSS` example since it doesn't make sense there.
> Fix pageFooter option and use double-bang on customMetadata

- templates/feature-overview.index.tmpl
Fixes #187 
This will insert several spaces in the generated `html` but since we do the same on the scenarios I guess it's fine. At least the space is now consistently inserted everywhere. :slightly_smiling_face:
> Ensure space is inserted between tags

- templates/assets/js/Chart.style.js
- templates/feature-overview.index.tmpl
- templates/features-overview.index.tmpl
Hi,
We noticed that the colors of the pie chart and the icons do not match (only the first two entries are correct).
The static lists in `templates/feature-overview.index.tmpl` [L146](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/templates/features-overview.index.tmpl#L146) and [L178](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/templates/features-overview.index.tmpl#L178) have been updated to match the lists in [`templates/assets/js/Chart.style.js`](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/templates/assets/js/Chart.style.js#L2) and `templates/feature-overview.index.tmpl`.
The changes have been checked with the `npm test` command which generates some reports in the `./.tmp/` directory.
The current …
> Fix: colors for pie chart are not consistent with icon colors

- templates/feature-overview.index.tmpl
Fixes #204 
Breaks the `description` field according to EOF modifiers. There is no alignment, i.e. the second line goes under the `Description` tag. Not a big fun of that but I don't think it's worth to have a deeper rework here. At the end of the day we added `plainDescription` to have custom formatting for the description anyway.
> Break scenario description on carriage returns

- templates/components/features-overview-custom-metadata.tmpl
- templates/components/features-overview.tmpl
**Environment (please complete the following information):**
- multiple-cucumber-html-reporter: commit 5c013eeadaa24e77ff3a166399455aba2d6e1134 (344. commit on the main branch)
**Config of multiple-cucumber-html-reporter**
Error can be reproduced with the `npm test` script in this repository.
**Describe the bug**
The 'Status' icon as well as the 'Pending/Skip' count in the feature details table is displayed incorrectly.
**To Reproduce**
1. Clone this repository
2. `git checkout 5c013eeadaa24e77ff3a166399455aba2d6e1134 # the 344. commit on the main branch`
3. `npm install`
4. `npm test`
5. Open the file `./.tmp/custom-metadata/index.html`
**Expected behavior**
The icons as well as the numbers in the table should be correct.
**Additional context**
Fixing the icon was rather simple.
For …
> fix incorrect status icon and pending/skip count in feature details table

- .github/ISSUE_TEMPLATE/--bug-report.md
- .github/ISSUE_TEMPLATE/--question.md
Super minor.
I wanted to revisit a bit the `readme` as well...but too much text and too little steam today. 🤣
At least this is an improvement, even if rather small.
> Fix typos in issue templates

- templates/style.css
Didn't open an issue for this, apologies. I just played around with the `css` and reached a point where I was happy enough to push it upstream.
The current dark mode theme always felt like a high contrast theme to me. Moreover, theme transition was afflicted by a flickage on the donut `div` sections. These `css` changes attempt to address these problems and provide a (better?) dark mode color combination based on guidelines found e.g. in [this awesome article](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/). Let me know what you think overall. Personally I think the new theme is pretty cool, ofc! 😄  
@wswebcreation following linter suggestions I've also removed some directives. It doesn't seem I've broken anything...but yeah please double-check that as well since the …
> Rework CSS to improve dark mode experience

- .gitignore
- lib/collect-jsons.js
- lib/generate-report.js
- package-lock.json
- package.json
- test/unit/collect-jsons.spec.js
- test/unit/data/json/after.hook.error.json
- test/unit/data/json/background.json
- test/unit/data/json/background2.json
- test/unit/data/json/before-and-after-hook.json
- test/unit/data/json/before.hook.error.json
- test/unit/data/json/embeddings.json
- test/unit/data/json/failure_report_v1.json
- test/unit/data/json/happy_flow_v1.json
- test/unit/data/json/with_rest_doc_string.json
- test/unit/data/output/merged-output.json
- test/unit/generate-json.spec.js
Fixes #195 
Used `node 14.20.0` which is the latest version of the current LTS. I'm personally in love with `yarn` but ofc I've used `npm` to do the update. But I would suggest to move to `yarn` since it's way faster.
Aside from the update, the PR drops `chalk` due to its limited usage in favour of using the colors directly. Maybe it's not pretty as before but it doesn't really make sense to introduce a library for a couple of simple usages.
[`istanbul` should be replaced by `nyc`](https://github.com/istanbuljs/nyc/issues/524)? I didn't delve into that option but I guess it should be taken in account. I would also consider to drop `moment` since it is used sparingly and its a huge dep. But I'll leave that to you as well since there are too many alternatives and too many opinions regarding …
> Update dependencies to latest available versions

- README.MD
Related to #214
Since the new `css` theme was merged let's update the readme to align documentation to the tuned dark theme.
> Update readme to show new dark mode theme

- .github/workflows/release.yml
- .release-it.json
- package-lock.json
- package.json
> fix: :bug: fixed failing release workflow

- lib/generate-report.js
Since Cucumber 10, all Text Attachments are as well Base64 encoded, which currently makes them unreadable in the HTML-Reports.
This fix was created by @lerhum and @WasiqB.
As my customer needs this piece of code, I fixed the findings as described.
All Credits go the the creators, I just want to help speeden up things :)
linked to https://github.com/WasiqB/multiple-cucumber-html-reporter/issues/298
Describe the bug
In the JSON formatter output of multiple-cucumber-html-reporter, all attachments, including those initially attached as plain text strings, are now Base64 encoded. This uniform encoding approach leads to ambiguity for consumers of the report, as they cannot distinguish whether an attachment was originally a plain text string or a different file format.
To Reproduce
Steps to …
> Decode base64-encoded Text Attachments

- lib/generate-report.js
- test/unit/data/custom-metadata-json/multiple_different_attachements.json
- test/unit/data/custom-metadata-json/undefined_scenarios_specified_v3.json
- test/unit/data/json/before-and-after-hook.json
- test/unit/data/json/embeddings.json
- test/unit/data/output/merged-output.json
Fix https://github.com/WasiqB/multiple-cucumber-html-reporter/issues/316
> Fix Json decoding

- lib/generate-report.js
- templates/components/scenarios.tmpl
- templates/style.css
A small PR to add video attachment support (webm) similar to the way image (png) is supported. This is change is primarily to support Playwright's video functionality.
See documentation: https://playwright.dev/docs/videos
> Create in report support for webm video in the report output

- lib/generate-report.js
- templates/feature-overview.index.tmpl
- templates/features-overview.index.tmpl
- test/test.js
Hi folks 👋 ,
this should be a fix for #374 .
I added a test for the useCDN case and reviewed the report files manually after the creation.
Looks good to me, but please do a double check, thanks 🤝 .
I hope this fulfills your contribution guideline. If not, don't hesitate to tell me what I have to change.
Best regards
Sven
> fix: dark mode in useCDN case
